### ISSUE TITLE
Add link to GNOME extension

### ISSUE THREAD

**Issue by timoschwarzer** [shlinkio/shlink.io#158]
Hi there! Thanks for making Shlink!

I made a simple GNOME extension that shortens URLs in your clipboard when pressing a keyboard shortcut.
I think it would be helpful for GNOME users to add a link to the system integrations list on the Shlink website :)

Extension page: https://extensions.gnome.org/extension/3282/shlink-url-shortener/

Source code: https://github.com/timoschwarzer/gnome-shell-extension-shlink

**Comment by acelaya** [comment]
Hey! Looks nice, thank you :)

Do you want to add it to the website? https://github.com/shlinkio/shlink.io

It should be enough by adding a new mdx document here https://github.com/shlinkio/shlink.io/tree/main/src/content/documentation/integrations, and then add the new section here https://github.com/shlinkio/shlink.io/blob/main/src/utils/docUtils.ts#L54

The last part of the path has to match the name of the new mdx file without extension.

It's important to explain how to install a gnome shell extension, and then how to use this particular one.

Some screenshot would also be nice.

**Comment by timoschwarzer** [comment]
@acelaya Thanks for the hints! :)

**Comment by acelaya** [comment]
Hey @timoschwarzer, I have just deployed the website including your contribution https://shlink.io/documentation/integrations/gnome-shell-extension/

Thanks a lot for it, and for building the extension.
