### ISSUE TITLE
Documentation related to mercure is outdated

### ISSUE THREAD

**Issue by loelkes** [shlinkio/shlink.io#229]
Options for `CORS_ALLOWED_ORIGINS` and `JWT_KEY` are deprecated. In my setup I used 

```
      MERCURE_PUBLISHER_JWT_KEY: ...
      MERCURE_SUBSCRIBER_JWT_KEY: ...
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins https://shlink.example.com

```
where shlink.example.com is the hostname for the shlink-web-client. I used the `MERCURE_PUBLISHER_JWT_KEY` for the shlink server. It does not seems to work but I don't know if it's a bug or if I configured something in the wrong way and I did not take a closer look yet.

Could you maybe document what "real time updates" means for the web client? What values are updates? Can I see the updates other than the number changing?

Loosely related to #212

**Comment by acelaya** [comment]
Relates to #212

**Comment by acelaya** [comment]
Al the documentation regarding real-time updates is here https://shlink.io/documentation/advanced/real-time-updates/

The specification for the async API can be found here https://api-spec.shlink.io/async-api/?version=v2.7.2
