### ISSUE TITLE
Shlink Documentation not available / offline?

### ISSUE THREAD

**Issue by cyb3rko** [shlinkio/shlink.io#237]
The whole documentation including every article as well as subdomains like https://api-spec.shlink.io/ can be opened, but only show an empty webpage without content.

Is this my problem? I tried to use multiple browsers and go via Tor, nothing worked for me.

**Comment by laontme** [comment]
https://app.shlink.io/ also seems offline. I tried firefox on windows, edge on windows, firefox on android, home wifi and mobile LTE
![изображение](https://user-images.githubusercontent.com/60975415/134460339-773cb9a1-1ef3-4f3f-be45-ee7aa60aaffa.png)

**Comment by acelaya** [comment]
Try again. Both should work now.

**Comment by laontme** [comment]
Fine. Works
