### ISSUE TITLE
Shlink Command Confusion

### ISSUE THREAD

**Issue by navjotjsingh** [shlinkio/shlink.io#251]
In the documentation https://github.com/shlinkio/shlink.io/blob/main/src/content/documentation/serve-with-swoole.mdx

The file mentions the command as `vendor/bin/laminas\ mezzio:swoole:start` but right after the file contents, the command is again mentioned as `vendor/bin/laminas mezzio:swoole:start`

Which command is the correct one?

**Comment by acelaya** [comment]
Mmmm, I'm not sure if I follow. What's the difference? 😅

**Comment by navjotjsingh** [comment]
The slash in front of laminas? If I use the second one, it says command not found.

**Comment by acelaya** [comment]
Oh, I see. The slash is just to escape the whitespace inside the script.

Later in the instructions the shlash is skipped because it's just mentioning the change in one command, but the slash itself is not part of the command, so it would be confusing.
