### ISSUE TITLE
iOS, iPadOS and MacOS Shortcuts-App Shortcut

### ISSUE THREAD

**Issue by MrDrache333** [shlinkio/shlink.io#274]
I'm using this tool for some time now and I love it.
Because I use it a lot on Apple Devices and also love the Shortcuts-app and their possibilities, I've created a shortcut to create links with Shlink. I Hope you like it and maybe add it to your Implementations-list 😃

**Supported Features**
- Create URLs without Custom Slug
- Create URLs with Custom Slug
- Respond to Errors during Link-Creation (Invalid Arguments, Slug already In Use etc.)
- Copy Short-URL to Clipboard
- Share URL with iOS/macOS Share-Sheet
- Create URLs by share Links to the Shortcut
- Create URLs by selecting Links on macOS and choose "Services" via Rightclick on the Link

**Coming Features**
- Request One 😉 
- Maybe some sort of Deleting Shortcuts or adding expiration/ limitation to them while creating
- Maybe some sort of requesting visiting Stats
- Maybe direct display of the QR-Code after creation

https://github.com/MrDrache333/shlink-ios-shortcut

**Comment by acelaya** [comment]
Hey!

I tend not to link to so young projects, because chances are they are abandoned.

If the project is still active in a couple of months and it's getting some traction, let me know 🙂
