### ISSUE TITLE
Add "Donate" button

### ISSUE THREAD

**Issue by filfreire** [shlinkio/shlink.io#37]
I suggest you should add a Donate button at the bottom of the `shlink` website, similarly to 
http://filfreire.com/Moneeee/

More doc on how to set this up: https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/donate_step_1/#

/cc @acelaya

**Comment by filfreire** [comment]
@acelaya you should also add it later on to the shlink project README 

 ¯\_(ツ)_/¯

**Comment by filfreire** [comment]
@acelaya 😄

**Comment by acelaya** [comment]
I hope you are happy :stuck_out_tongue: https://github.com/shlinkio/shlink.io/pull/38

**Comment by filfreire** [comment]
@acelaya 💸 💸 💸
