### ISSUE TITLE
Incorrect docker run example for shlink-web-client

### ISSUE THREAD

**Issue by cn-ml** [shlinkio/shlink.io#600]
The run command for the web-client lists `-p 8000:80` as a port in the [documentation](https://github.com/shlinkio/shlink.io/commit/154c33ca166295c12ed39bcb945d2163dd0ea162#r141253935).

The actual port as specified in the nginx config is `listen 8080 default_server;`. This will lead to bad gateway errors.

**Comment by acelaya** [comment]
Yep, that seems to have been overlooked here https://github.com/shlinkio/shlink.io/pull/573/files

Do you want to provide a PR?
