### ISSUE TITLE
Compatibility: Dropshare & Shortshare

### ISSUE THREAD

**Issue by tjosten** [shlinkio/shlink.io#835]
Hi there,

just letting you know that Shlink is compatible with both [Dropshare](https://dropshare.app) and [Shortshare](https://shortshare.app). Instructions for set up are here: https://support.dropshare.app/hc/en-us/articles/23560649959826-How-to-set-up-Shlink-as-URL-shortener

Cheers,
Timo

**Comment by acelaya** [comment]
I don't see a dedicated section explaining it for Shortshare here https://support.shortshare.app/. I guess it's simply because it's the same as for Dropshare.

Also, are you in any way endorsed with those products?

**Comment by tjosten** [comment]
Yeah, sorry, you're right. It works the same way for both apps. 

And yes, I am. Both are my apps.

**Comment by acelaya** [comment]
Just added a link to the documentation.
